// 사용한 API : TMDB 현재 한국에서 상영 중인 영화 API
// API Document : https://developers.themoviedb.org/3/movies/get-now-playing
// Request : https://api.themoviedb.org/3/movie/now_playing?api_key=c4e59022826dc465ea5620d6adaa6813&language=ko&page=1&region=KR

// 아래는 Response Data
export const dummy = {
  dates: {
    maximum: "2024-04-24",
    minimum: "2024-03-13",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
      genre_ids: [28, 878, 12, 14],
      id: 823464,
      original_language: "en",
      original_title: "Godzilla x Kong: The New Empire",
      overview:
        "고질라 X 콩, 이번에는 한 팀이다! ‘고질라’ VS ‘콩’, 두 타이탄의 전설적인 대결 이후 할로우 어스에 남은 ‘콩’은 드디어 애타게 찾던 동족을 발견하지만 그 뒤에 도사리고 있는 예상치 못한 위협에 맞닥뜨린다. 한편, 깊은 동면에 빠진 ‘고질라’는 알 수 없는 신호로 인해 깨어나고 푸른 눈의 폭군 ‘스카 킹’의 지배 아래 위기에 처한 할로우 어스를 마주하게 된다. 할로우 어스는 물론, 지구상에도 출몰해 전세계를 초토화시키는 타이탄들의 도발 속에서 ‘고질라’와 ‘콩’은 사상 처음으로 한 팀을 이뤄 반격에 나서기로 하는데…",
      popularity: 2002.241,
      poster_path: "/4z1VMmlxHrziG45901esjB4dpIa.jpg",
      release_date: "2024-03-27",
      title: "고질라 X 콩: 뉴 엠파이어",
      video: false,
      vote_average: 6.679,
      vote_count: 668,
    },
    {
      adult: false,
      backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
      genre_ids: [16, 28, 10751, 35, 14],
      id: 1011985,
      original_language: "en",
      original_title: "Kung Fu Panda 4",
      overview:
        "마침내 내면의 평화… 냉면의 평화…가 찾아왔다고 믿는 용의 전사 ‘포’ 이젠 평화의 계곡의 영적 지도자가 되고, 자신을 대신할 후계자를 찾아야만 한다. “이제 용의 전사는 그만둬야 해요?” 용의 전사로의 모습이 익숙해지고 새로운 성장을 하기보다 지금 이대로가 좋은 ‘포’ 하지만 모든 쿵푸 마스터들의 능력을 그대로 복제하는 강력한 빌런 ‘카멜레온’이 나타나고 그녀를 막기 위해 정체를 알 수 없는 쿵푸 고수 ‘젠’과 함께 모험을 떠나게 되는데… 포는 가장 강력한 빌런과 자기 자신마저 뛰어넘고 진정한 변화를 할 수 있을까?",
      popularity: 1949.726,
      poster_path: "/1ZNOOMmILNUzVYbzG1j7GYb5bEV.jpg",
      release_date: "2024-04-10",
      title: "쿵푸팬더 4",
      video: false,
      vote_average: 7.134,
      vote_count: 1136,
    },
    {
      adult: false,
      backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
      genre_ids: [28, 14],
      id: 634492,
      original_language: "en",
      original_title: "Madame Web",
      overview:
        "우연한 사고로 미래를 볼 수 있게 된 구급대원 '캐시 웹'이 거미줄처럼 엮인 운명을 마주하며, 같은 예지 능력을 가진 적 '심스'에 맞서 세상을 구할 히어로 '마담 웹'으로 거듭나게 되는 과정을 그린 마블의 NEW 히어로 드라마",
      popularity: 628.474,
      poster_path: "/eqEzpQNusV9XSdnA9HAvlLMeuPs.jpg",
      release_date: "2024-03-13",
      title: "마담 웹",
      video: false,
      vote_average: 5.647,
      vote_count: 1097,
    },
    {
      adult: false,
      backdrop_path: "/5cCfqeUH2f5Gnu7Lh9xepY9TB6x.jpg",
      genre_ids: [14, 12, 35],
      id: 967847,
      original_language: "en",
      original_title: "Ghostbusters: Frozen Empire",
      overview:
        "무더운 여름의 뉴욕의 어느 날, 고대 유물 속 깨어난 데스칠로 인해 정체불명의 냉기가 몰려오고 마침내 도시는 얼어붙고 만다. 유령을 퇴치하는 그루버슨과 라이즈 버스터즈 멤버들은 얼어붙은 세상을 깨부수기 위해 유령 군단을 쫓기 시작하는데…",
      popularity: 502.968,
      poster_path: "/mGzSIfzmcf9H91DS06cnka1SYrP.jpg",
      release_date: "2024-04-17",
      title: "고스트버스터즈: 오싹한 뉴욕",
      video: false,
      vote_average: 6.527,
      vote_count: 262,
    },
    {
      adult: false,
      backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
      genre_ids: [28, 53, 10752],
      id: 969492,
      original_language: "en",
      original_title: "Land of Bad",
      overview:
        "라스베이거스 공군 기지의 베테랑 드론 조종사 리퍼(러셀 크로우)는 델타포스 티어-원 부대의 CIA 요원 구출작전 지원임무를 맡게 된다. 슈가(마일로 벤티밀리아), 아벨(루크 헴스워스)이 이끄는 티어-원 부대는 CIA 요원이 사라진 필리핀 남서부, 미스터리한 지형의 홀로 섬 정찰에 나서고, 이 위험천만한 작전을 위해 JTAC 신입요원 키니(리암 헴스워스)와 실전 경험이 많은 군인 비숍(리키 휘틀)까지 합류한다. 그러나 도망칠 곳도 숨을 곳도 없는 섬에서 이들은 곧 적에게 노출되고 피할 수 없는 전면전이 펼쳐지며 상황은 급반전을 맞이한다. 무기도, 통신장비도 없는 정글에 홀로 갇힌 키니, 동료를 구하고 작전을 성공시켜야 할 그에게 남은 건, 눈과 귀가 되어주는 드론 조종사 리퍼뿐! 누구도 포기하지 않는다, 끝까지 살아남는다!",
      popularity: 434.119,
      poster_path: "/6yrDUJyl1naOn3zfOhFPE9ZGsfP.jpg",
      release_date: "2024-03-13",
      title: "랜드 오브 배드",
      video: false,
      vote_average: 7.21,
      vote_count: 583,
    },
    {
      adult: false,
      backdrop_path: "/mIBG74mhGEJnBubhYLkCtvplcNr.jpg",
      genre_ids: [27],
      id: 437342,
      original_language: "en",
      original_title: "The First Omen",
      overview:
        "수녀가 되기 위해 로마에 가게 된 마거릿. 그곳에서 새로운 삶을 시작하려는 그때, 믿음을 뒤흔드는 어둠의 그림자를 마주한다.  서서히 조여오는 끔찍한 공포가 마침내 정체를 드러내기 시작하는데...",
      popularity: 363.27,
      poster_path: "/a0laJ0AVyhQONK3TNEJKqvB2uM2.jpg",
      release_date: "2024-04-03",
      title: "오멘: 저주의 시작",
      video: false,
      vote_average: 6.7,
      vote_count: 106,
    },
    {
      adult: false,
      backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
      genre_ids: [28, 53, 18],
      id: 866398,
      original_language: "en",
      original_title: "The Beekeeper",
      overview:
        "법 위에 있는 비밀 기관 '비키퍼' 그곳의 전설로 남은 탑티어 에이전트 '애덤 클레이'는 기관의 눈을 피해 자취를 감추고 양봉가로 살아간다. 그러던 어느 날, 거대 보이스 피싱 조직으로부터 유일한 친구 '엘로이즈'를 잃게 된 그는 피의 복수를 위해 잠재웠던 진짜 모습을 드러내기 시작하는데....",
      popularity: 290.037,
      poster_path: "/ekHemOB84SoKi6fqG0ciwvKWM2i.jpg",
      release_date: "2024-04-03",
      title: "비키퍼",
      video: false,
      vote_average: 7.476,
      vote_count: 2035,
    },
    {
      adult: false,
      backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
      genre_ids: [18, 12],
      id: 618588,
      original_language: "en",
      original_title: "Arthur the King",
      overview:
        "어드벤처 레이싱 팀 주장 ‘마이클’은 최고로 힘든 지형과 날씨의 도미니카 공화국에서 700KM를 질주해야 한다! 여러 단계를 통과하던 중, '마이클' 앞에 떠돌이 개 '아서'가 나타나고 그의 팀을 따라다니기 시작하는데, '아서'를 포기해야만 우승 할 수 있는 상황..!  마지막 도전! 우승을 놓칠 수 없는 경기! ‘’아서’와 끝가지 함께 할 수 있을까?",
      popularity: 145.056,
      poster_path: "/a9B0PGRIhmOGRmpKdNR46id30Pt.jpg",
      release_date: "2024-04-17",
      title: "아서",
      video: false,
      vote_average: 6.35,
      vote_count: 30,
    },
    {
      adult: false,
      backdrop_path: "/hIeEpk2w1dnC9ly9ZJwwbunH2Cx.jpg",
      genre_ids: [16, 35, 18, 10751],
      id: 838240,
      original_language: "es",
      original_title: "Robot Dreams",
      overview:
        "뉴욕 맨해튼에서 홀로 외롭게 살던 ‘도그’는 TV를 보다 홀린 듯 반려 로봇을 주문하고 그와 둘도 없는 단짝이 되어 행복한 나날을 보낸다. 그러던 어느 날, 해수욕장에 놀러간 ‘도그’와 ‘로봇’은 예기치 못한 상황에 휩쓸려 이별을 맞이하게 되는데···",
      popularity: 146.754,
      poster_path: "/3TfgJPOx7lzuopbXimsvYGq4vn6.jpg",
      release_date: "2024-03-13",
      title: "로봇 드림",
      video: false,
      vote_average: 7.902,
      vote_count: 264,
    },
    {
      adult: false,
      backdrop_path: "/1ZSKH5GGFlM8M32K34GMdaNS2Ew.jpg",
      genre_ids: [10402, 36, 18],
      id: 802219,
      original_language: "en",
      original_title: "Bob Marley: One Love",
      overview:
        "혁명적인 음악으로 사랑과 화합의 메시지를 전한 시대의 아이콘 ‘밥 말리’의 전설적인 무대와 나아가 세상을 바꾼 그의 뜨거웠던 삶을 그린 감동 음악 영화",
      popularity: 149.864,
      poster_path: "/fgUmmFzdESEEKfUcDJ3JKReDqUT.jpg",
      release_date: "2024-03-13",
      title: "밥 말리: 원 러브",
      video: false,
      vote_average: 7,
      vote_count: 489,
    },
    {
      adult: false,
      backdrop_path: "/504GSaoxBA5nLlcMsJfjzLZEKUp.jpg",
      genre_ids: [18, 10749],
      id: 937287,
      original_language: "en",
      original_title: "Challengers",
      overview:
        "테니스 영재에서 코치가 된 타시는 코트 안팎에서 늘 자신감이 넘친다. 반면 타시의 남편 아트는 테니스 선수로 활동 중이나 연속으로 부진을 겪고 있어 타시는 이를 타계할 전략을 세우지만 예상치 못한 전환점이 찾아온다. 아트의 옛 테니스 동료이자 베프였던 패트릭은 현재 별 볼일없는 테니스 선수가 되어 아트와 맞붙게 되고, 타시의 전 남자친구이기도 했던 패트릭이 나타나면서 과거와 현재가 충돌하고 긴장이 고조되는 가운데 타시는 남편의 승리를 위해 어떤 대가를 치러야 할지 고민하기 시작한다.",
      popularity: 117.36,
      poster_path: "/iUDG0gsPZxNm9IOLqpIUZiUMVMZ.jpg",
      release_date: "2024-04-24",
      title: "챌린저스",
      video: false,
      vote_average: 9,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/zVDJ4cRgSpHlILSm7kGiklHQ6O7.jpg",
      genre_ids: [16, 35, 12, 28],
      id: 1062807,
      original_language: "ja",
      original_title: "劇場版 SPY×FAMILY CODE: White",
      overview:
        "세계 각국이 물밑에서 치열하게 정보전을 펼치고 있는 시대. 서로의 정체를 숨긴 채 결성된 위장 가족의 아버지 '로이드(스파이)'와 어머니 '요르(암살자)’, 딸 '아냐(초능력자)'는 각자의 목표를 위해 비밀스러운 임무를 수행한다. 오퍼레이션 올빼미 작전을 위해 첫 가족 여행을 떠나던 중, ‘아냐’는 열차 안에서 수상한 캐리어를 발견하고 그 안의 초콜릿을 실수로 그만 삼켜버리고 마는데… 엄청난 비밀이 숨겨진 초콜릿과 여행지에서 생기는 해프닝의 연속!! 세계의 명운은, 다시 이 위장 가족에게 맡겨졌다!",
      popularity: 88.301,
      poster_path: "/rlMJfgo8xXHkqgICy9kh4CWyQTu.jpg",
      release_date: "2024-03-20",
      title: "극장판 스파이 패밀리 코드 : 화이트",
      video: false,
      vote_average: 7.1,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: "/klb3yODwKMRle19EcvdeSatEZL7.jpg",
      genre_ids: [27, 53],
      id: 1072342,
      original_language: "en",
      original_title: "Night Swim",
      overview:
        "넓은 수영장이 있는 새집으로 이사 온 후 더할 나위 없는 행복을 느끼고 있는 ‘레이’ 가족. 하지만 완벽한 순간도 잠시, 물속에서 혼자 수영하게 되면 숨막히게 조여오는 공포에 잠기게 되는데… ※절대 혼자 수영하지 말 것 ※ 진짜 무서운 건 이 아래에 있어",
      popularity: 65.933,
      poster_path: "/4Q20D0HCYNHwvTna4OXJNCDvyI3.jpg",
      release_date: "2024-03-20",
      title: "나이트 스윔",
      video: false,
      vote_average: 5.741,
      vote_count: 370,
    },
    {
      adult: false,
      backdrop_path: "/j11RoLbvHGmJsBHcKqvbZxc5drh.jpg",
      genre_ids: [18, 28, 53],
      id: 1053592,
      original_language: "es",
      original_title: "Todos los nombres de Dios",
      overview:
        "공항에서 손님을 기다리던 택시 운전사 산티, 일순간 공항은 폭탄 테러로 인해 혼비백산 상태가 되고 산티는 그곳에서 테러리스트인 함자에 의해 인질로 잡히게 된다. 산티는 테러리스트에 의해 움직임을 멈추면 폭탄이 폭발해버리는 위험천만한 조끼를 입고 마드리드 중심부를 걸어 다니는 인간 폭탄이 되는데…",
      popularity: 67.777,
      poster_path: "/kx3X00Q1XSozAA60gpVFCVxMNQm.jpg",
      release_date: "2024-04-17",
      title: "올 더 네임즈 오브 갓",
      video: false,
      vote_average: 6.465,
      vote_count: 86,
    },
    {
      adult: false,
      backdrop_path: "/97MOhHIgU6ZdLcB9DrAhx3WAqrU.jpg",
      genre_ids: [18, 35],
      id: 839369,
      original_language: "en",
      original_title: "May December",
      overview:
        "신문 1면을 장식하며 미국을 떠들썩하게 만든 충격적인 로맨스의 주인공들인 그레이시와 그보다 23살 어린 남편 조. 20여 년이 흐른 어느 날, 영화에서 그레이시를 연기하게 된 인기 배우 엘리자베스가 캐릭터 연구를 위해 그들의 집에 머물게 된다. 부부의 일상과 사랑을 깊숙이 들여다보는 엘리자베스의 시선과 과거의 진실을 파헤치는 그의 잇따른 질문들이 세 사람 사이에 균열을 가져오는데…",
      popularity: 74.169,
      poster_path: "/zrOCKbNIA62cSajizx5Sxb0LuPh.jpg",
      release_date: "2024-03-13",
      title: "메이 디셈버",
      video: false,
      vote_average: 6.759,
      vote_count: 517,
    },
    {
      adult: false,
      backdrop_path: "/dSyNPeQa4KnWSluU2rP3yansB4P.jpg",
      genre_ids: [18],
      id: 1156125,
      original_language: "ja",
      original_title: "悪は存在しない",
      overview:
        "아직 개발이 되지 않은 작은 산골 마을에 글램핑장 설명회가 열린다. 도시에서 온 사람들로 인해 타쿠미와 그의 딸 하나에게 소동이 벌어진다.",
      popularity: 47.374,
      poster_path: "/3iwz185iNPpnoTxDTOj973KSWm2.jpg",
      release_date: "2024-03-27",
      title: "악은 존재하지 않는다",
      video: false,
      vote_average: 6.944,
      vote_count: 62,
    },
    {
      adult: false,
      backdrop_path: "/39bnNb5vty4Iy1koPcJMY625ga9.jpg",
      genre_ids: [12, 10749, 35, 18, 14],
      id: 837335,
      original_language: "it",
      original_title: "La chimera",
      overview:
        "도굴꾼 아르투에겐 땅속 유물을 감지하는 특별한 능력이 있다. 부의 꿈에 도취된 동료들 사이에서 그는 잃어버린 연인, 베니아미나를 찾아 헤맨다.",
      popularity: 60.035,
      poster_path: "/jTHIXi5mcGHetKuGfoAZQIdtLtm.jpg",
      release_date: "2024-04-03",
      title: "키메라",
      video: false,
      vote_average: 7.6,
      vote_count: 199,
    },
    {
      adult: false,
      backdrop_path: "/mO9oOVXM8tTlC11VFM4FBBNnL3f.jpg",
      genre_ids: [80, 28, 18],
      id: 1017163,
      original_language: "ko",
      original_title: "범죄도시 4",
      overview:
        "신종 마약 사건 3년 뒤, 괴물형사 마석도와 서울 광수대는 배달앱을 이용한 마약 판매 사건을 수사하던 중 수배 중인 앱 개발자가 필리핀에서 사망한 사건이 대규모 온라인 불법 도박 조직과 연관되어 있음을 알아낸다. 필리핀에 거점을 두고 납치, 감금, 폭행, 살인 등으로 대한민국 온라인 불법 도박 시장을 장악한 특수부대 용병 출신의 빌런 백창기와 한국에서 더 큰 판을 짜고 있는 IT업계 천재 CEO 장동철. 마석도는 더 커진 판을 잡기 위해 장이수에게 뜻밖의 협력을 제안하고 광역수사대는 물론, 사이버수사대까지 합류해 범죄를 소탕하기 시작하는데…",
      popularity: 44.65,
      poster_path: "/h1YarEjeYurkAwXgfY1RDMVCiin.jpg",
      release_date: "2024-04-24",
      title: "범죄도시 4",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/a8VgPlIQaX2WfUfYxhF4ItpkTO.jpg",
      genre_ids: [18, 53],
      id: 812037,
      original_language: "fr",
      original_title: "L’été dernier",
      overview:
        "남편 피에르와 함께 입양한 두 딸을 키우며 완벽한 삶을 살고 있는 청소년 전문 변호사 안느. 어느 날, 남편이 전처와 낳은 아들 테오가 학교에서 사고를 치며 안느와 테오는 한집에 살게 된다. 테오는 어딘가 외로워보이는 안느에게 적극적으로 다가가고 안느는 그런 테오에게 걷잡을 수 없이 빠져들며 그와 금지된 사랑을 나누게 되는데…",
      popularity: 39.625,
      poster_path: "/1T3nJiKJyIHNFZoiSTYOwDJc7lH.jpg",
      release_date: "2024-04-03",
      title: "라스트 썸머",
      video: false,
      vote_average: 5.984,
      vote_count: 91,
    },
    {
      adult: false,
      backdrop_path: "/yvotjJ9nKlPKiwc8PtktIjRCkof.jpg",
      genre_ids: [18, 36, 10749],
      id: 921452,
      original_language: "fr",
      original_title: "Jeanne du Barry",
      overview:
        "1743년 가난한 재봉사의 사생아로 태어난 잔느 보베르니에. 성인이 된 잔느는 사교계의 여자로 이름을 날리던 중 베리 백작의 계획으로 루이 15세 앞까지 얼굴을 보이는 기회를 얻게 된다. 그때 루이 15세는 잔느에게 첫눈에 반하게 되고, 천민인 그녀를 급기야 베르사유 궁에 몰래 들여 함께 은밀한 생활을 하게 되는데...",
      popularity: 27.516,
      poster_path: "/wpvVaX2h3Rbm3UHHUb24nQRgqNI.jpg",
      release_date: "2024-04-03",
      title: "잔 뒤 바리",
      video: false,
      vote_average: 7.007,
      vote_count: 350,
    },
  ],
  total_pages: 4,
  total_results: 79,
};
